server: 
  port: 9001
spring: 
#  mvc: 
#    view: 
#      prefix: /WEB-INF/html/
#      suffix: .jsp 
  devtools: 
    livereload: 
      enabled: true 
  mail:
    host: smtp.gmail.com
    port: 587
    username: chadong4052@gmail.com
    password: jdxkcwkbgezwyiym
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          naver:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            client-secret: 28Z8SlAezS
            scope: name,email,nickname
            client-id: S4vf7M94cALtBOCIxY7Q 
            client-name: Naver
            authorization-grant-type: authorization_code
        provider:
          naver:
            user-name-attribute: response
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            user-info-uri: https://openapi.naver.com/v1/nid/me
            token-uri: https://nid.naver.com/oauth2.0/token      
              
#mysql 
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver 
    url: jdbc:mysql://finalproject.chrgn3ko5veh.ap-northeast-2.rds.amazonaws.com:3306/finalDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: finaladmin
    password: a123456789
    
#mybatis setting 
mybatis: 
  type-aliases-package: data.dto, data.mapper 
  mapper-locations: 
  - /mapper/**/*.xml